language: csharp
solution: visualcsc.sln
mono: none
dotnet: 3.1.101
notifications:
    email:
      - iordan415586@gmail.com

    

script:
    - dotnet restore
    #- msbuild /p:Configuration=Release solution-name.sln
    #- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
services:
    - docker
before_install:
    - docker build -t hyst3r1a/visualcsc .
    - docker ps -a
    - docker build -t my-prometheus ./tmp
    #- docker run -p 9090:9090 my-prometheus
    - docker ps -a
    - docker run -d -p 8080:80 --name visualcsc hyst3r1a/visualcsc
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.example.com


after_succes:
    #- sh .travis/deploy_dockerhub.sh
    #- test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
deploy:
    provider: heroku
    username: $DOCKER_USERNAME
    password: $DOCKER_PASSWORD
    api_key: $DOCKER_PASSWORD
    app: visualcsc
    run: 
        - "docker run -d -p 8080:80 --name VisualCSC hyst3r1a/visualcsc"
        - "docker run -p 9090:9090 -v /tmp/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus"
        
